/**
 * Instasure.ca design tokens — lifted 1:1 from the Stitch mockups
 * (home / quote generator / quote results / knowledge center, mobile + desktop)
 * and compiled at build time instead of the CDN play script (better LCP/CLS).
 */
const typography = require('@tailwindcss/typography');

const colors = {
  'on-primary-fixed': '#081c31',
  'on-tertiary-fixed-variant': '#8a1c10',
  tertiary: '#0f0000',
  'surface-container': '#e5eeff',
  'on-secondary': '#ffffff',
  'on-tertiary-container': '#e05a47',
  'on-primary': '#ffffff',
  'on-secondary-fixed-variant': '#005233',
  'inverse-surface': '#213145',
  'inverse-on-surface': '#eaf1ff',
  'surface-container-high': '#dce9ff',
  'surface-bright': '#f8f9ff',
  'primary-container': '#0a1e33',
  'on-surface-variant': '#44474d',
  'on-error': '#ffffff',
  'on-tertiary': '#ffffff',
  'primary-fixed': '#d2e4ff',
  'surface-variant': '#d3e4fe',
  secondary: '#006c46',
  primary: '#00030a',
  'tertiary-fixed-dim': '#ffb4a8',
  'on-primary-fixed-variant': '#36485f',
  'secondary-fixed': '#73fbb8',
  outline: '#74777d',
  'secondary-container': '#6ff8b5',
  error: '#ba1a1a',
  'surface-container-lowest': '#ffffff',
  'tertiary-container': '#440100',
  'surface-container-low': '#eff4ff',
  'on-error-container': '#93000a',
  'on-tertiary-fixed': '#410100',
  'primary-fixed-dim': '#b5c8e4',
  'error-container': '#ffdad6',
  'on-background': '#0b1c30',
  'on-primary-container': '#7486a0',
  'tertiary-fixed': '#ffdad4',
  'secondary-fixed-dim': '#53de9e',
  'on-surface': '#0b1c30',
  'surface-container-highest': '#d3e4fe',
  surface: '#f8f9ff',
  'on-secondary-fixed': '#002112',
  'on-secondary-container': '#007149',
  'outline-variant': '#c4c6cd',
  'surface-tint': '#4e6078',
  background: '#f8f9ff',
  'surface-dim': '#cbdbf5',
  'inverse-primary': '#b5c8e4',
};

const font = ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'sans-serif'];

module.exports = {
  content: ['./views/**/*.ejs', './public/js/**/*.js', './src/**/*.js'],
  theme: {
    extend: {
      colors,
      borderRadius: { DEFAULT: '0.25rem', lg: '0.5rem', xl: '0.75rem', '2xl': '1rem', '3xl': '1.5rem', full: '9999px' },
      spacing: {
        margin: '1rem',
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        'margin-tablet': '2rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xs': '0.25rem',
        'space-lg': '1.5rem',
        'margin-desktop': '3rem',
      },
      maxWidth: { site: '1160px', prose: '72ch' },
      fontFamily: {
        sans: font,
        'headline-lg': font, 'price-hero-mobile': font, 'price-hero': font, 'headline-lg-mobile': font,
        'body-sm': font, 'label-lg': font, 'label-sm': font, 'body-lg': font, 'headline-md': font,
        'headline-sm': font, 'body-md': font, 'display-lg': font, 'display-lg-mobile': font, 'label-md': font,
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'price-hero-mobile': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'price-hero': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['15px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      typography: () => ({
        instasure: {
          css: {
            '--tw-prose-body': colors['on-surface'],
            '--tw-prose-headings': colors['primary-container'],
            '--tw-prose-lead': colors['on-surface-variant'],
            '--tw-prose-links': colors.secondary,
            '--tw-prose-bold': colors['on-surface'],
            '--tw-prose-counters': colors.secondary,
            '--tw-prose-bullets': colors.secondary,
            '--tw-prose-hr': colors['surface-container-high'],
            '--tw-prose-quotes': colors['primary-container'],
            '--tw-prose-quote-borders': colors['secondary-fixed-dim'],
            '--tw-prose-captions': colors['on-surface-variant'],
            '--tw-prose-code': colors['primary-container'],
            '--tw-prose-th-borders': colors['surface-container-high'],
            '--tw-prose-td-borders': colors['surface-container'],
          },
        },
      }),
    },
  },
  plugins: [typography],
};
