'use strict';
/**
 * Regenerates docs/KEYWORDS.md and docs/keywords.csv from src/data/keywords.js,
 * so the strategy docs and the admin keyword map always use the same data.
 *   node scripts/keyword-report.js
 */
const fs = require('node:fs');
const path = require('node:path');
const { keywords } = require('../src/data/keywords');
const geo = require('../src/data/geo');
const { csvCell } = require('../src/lib/util');

const ROOT = path.join(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');
fs.mkdirSync(DOCS, { recursive: true });

const num = (n) => new Intl.NumberFormat('en-CA').format(n);
const esc = (s) => String(s ?? '').replace(/\|/g, '\\|');
const byVol = (a, b) => b.volume - a.volume;
const planned = (k) => k.target_path ? `\`${k.target_path}\`` : `*planned*${(/(\/[a-z0-9\-/{}]+\/)/.exec(k.notes || '') || [])[1] ? ` \`${/(\/[a-z0-9\-/{}]+\/)/.exec(k.notes)[1]}\`` : ''}`;
const cityName = (slug) => (geo.cities.find((c) => c.slug === slug) || {}).name || slug;
const provAbbr = (code) => (geo.provinceByCode[code] || {}).abbr || '';

function table(rows, cols) {
  const head = `| ${cols.map((c) => c[0]).join(' | ')} |\n|${cols.map((c) => (c[2] === 'r' ? '---:' : '---')).join('|')}|`;
  return [head, ...rows.map((r, i) => `| ${cols.map((c) => esc(c[1](r, i))).join(' | ')} |`)].join('\n');
}

const levels = ['local', 'provincial', 'national'];
const L = Object.fromEntries(levels.map((l) => [l, keywords.filter((k) => k.level === l).sort(byVol)]));
const total = keywords.reduce((s, k) => s + k.volume, 0);

// Cluster summary
const clusters = {};
for (const k of keywords) {
  const c = (clusters[k.cluster] ||= { cluster: k.cluster, n: 0, v: 0, mapped: 0, p1: 0 });
  c.n++; c.v += k.volume; if (k.target_path) c.mapped++; if (k.priority === 1) c.p1++;
}
const clusterRows = Object.values(clusters).sort((a, b) => b.v - a.v);

// City × product matrix (modelled volume of the head phrase)
const MATRIX_PRODUCTS = [['car-insurance', 'Car'], ['home-insurance', 'Home'], ['tenant-insurance', 'Tenant'], ['condo-insurance', 'Condo'], ['life-insurance', 'Life'], ['business-insurance', 'Business'], ['super-visa-insurance', 'Super visa']];
const cityRows = geo.cities.filter((c) => !geo.provinceByCode[c.prov].territory).map((c) => {
  const r = { c, total: 0 };
  for (const [p] of MATRIX_PRODUCTS) {
    const k = L.local.find((x) => x.city === c.slug && x.product === p && !/^(cheap|how much)/.test(x.keyword) && !/[àâéèêîôûç]/.test(x.keyword));
    r[p] = k ? k.volume : 0; r.total += r[p];
  }
  return r;
}).sort((a, b) => b.total - a.total);

const cols = (extra = []) => [
  ['#', (k, i) => i + 1, 'r'],
  ['Keyword', (k) => k.keyword],
  ...extra,
  ['Est. volume/mo', (k) => num(k.volume), 'r'],
  ['KD', (k) => k.difficulty, 'r'],
  ['Intent', (k) => k.intent],
  ['Priority', (k) => `P${k.priority}`],
  ['Who ranks today', (k) => k.competitors || ''],
  ['Target page', (k) => planned(k)],
];

const md = `# instasure.ca keyword map

_Generated by \`node scripts/keyword-report.js\` from \`src/data/keywords.js\`. Do not edit by hand. The same ${num(keywords.length)} keywords are seeded into **Admin → SEO → Keyword map**, where they can be filtered, ranked and exported._

> **Volumes are modelled estimates, not measured data.** The October 2026 competitor research could see competitors' pages, titles and on-page data through search results, but it had no access to a keyword tool. National head-term figures are order-of-magnitude priors for Canada. Provincial and city figures are derived from them with a population model (documented at the top of \`src/data/keywords.js\`) and rounded to two significant figures. Use them to **order** the work. Before you forecast traffic or budget, import a Google Keyword Planner (or Ahrefs/Semrush) export in the admin: matching rows are overwritten and marked with their real source.

**Columns**
- **Est. volume/mo:** modelled monthly Google searches in Canada.
- **KD:** modelled difficulty from 0 to 100. It rises with the number of competitor pages seen for that exact term.
- **Priority:** P1 to P5. P1 means enrich and promote this page first. It blends volume, lead value, difficulty, competitor gaps and whether we can serve the province.
- **Who ranks today:** competitors with a dedicated page in the October 2026 search results.
- **Target page:** a live URL on this build, or *planned* when the page is not built yet (the content backlog).

## Summary

| Level | Keywords | Est. monthly searches | Mapped to a live page |
|---|---:|---:|---:|
${levels.map((l) => `| ${l === 'local' ? 'Local (city)' : l === 'provincial' ? 'Provincial' : 'Canada-wide'} | ${L[l].length} | ${num(L[l].reduce((s, k) => s + k.volume, 0))} | ${L[l].filter((k) => k.target_path).length} |`).join('\n')}
| **Total** | **${keywords.length}** | **${num(total)}** | **${keywords.filter((k) => k.target_path).length}** |

### By topic cluster (sorted by volume)

${table(clusterRows, [['Cluster', (c) => c.cluster], ['Keywords', (c) => c.n, 'r'], ['Est. volume/mo', (c) => num(c.v), 'r'], ['P1 keywords', (c) => c.p1, 'r'], ['Mapped', (c) => `${Math.round((c.mapped / c.n) * 100)}%`, 'r']])}

---

## 1. Local (city) keywords, sorted by volume

The top 80 city keywords. The full list of ${L.local.length} is in the admin and in \`docs/keywords.csv\`.

${table(L.local.slice(0, 80), cols([['City', (k) => k.city ? `${cityName(k.city)}, ${provAbbr(k.province)}` : '']]))}

### City × product demand matrix

Modelled monthly volume for "{product} {city}". Cities are sorted by total demand, and a dash means below 20 searches a month.

${table(cityRows, [['City', (r) => `${r.c.name}, ${provAbbr(r.c.prov)}`], ['Tier', (r) => r.c.tier, 'r'], ...MATRIX_PRODUCTS.map(([p, label]) => [label, (r) => (r[p] ? num(r[p]) : '–'), 'r']), ['Total', (r) => num(r.total), 'r']])}

---

## 2. Provincial keywords, sorted by volume

${table(L.provincial, cols([['Province', (k) => provAbbr(k.province)]]))}

---

## 3. Canada-wide keywords, sorted by volume

${table(L.national, cols())}

---

## 4. Priority 1: enrich and promote these pages first

${table(keywords.filter((k) => k.priority === 1).sort(byVol), cols([['Level', (k) => k.level]]))}

---

## 5. Content backlog: keywords with no live page yet

${table(keywords.filter((k) => !k.target_path).sort(byVol), [['#', (k, i) => i + 1, 'r'], ['Keyword', (k) => k.keyword], ['Level', (k) => k.level], ['Est. volume/mo', (k) => num(k.volume), 'r'], ['Priority', (k) => `P${k.priority}`], ['Plan', (k) => k.notes || '']])}
`;

fs.writeFileSync(path.join(DOCS, 'KEYWORDS.md'), md);

const csvCols = ['keyword', 'level', 'product', 'province', 'city', 'volume', 'volume_source', 'difficulty', 'intent', 'cluster', 'competitors', 'target_path', 'priority', 'notes'];
const csv = [csvCols.join(','), ...[...keywords].sort((a, b) => a.priority - b.priority || b.volume - a.volume).map((k) => csvCols.map((c) => csvCell(k[c])).join(','))].join('\n') + '\n';
fs.writeFileSync(path.join(DOCS, 'keywords.csv'), csv);

console.log(`docs/KEYWORDS.md and docs/keywords.csv written (${keywords.length} keywords, ${num(total)} est. searches/mo)`);
